name: Release Plugin

on:
  workflow_dispatch:
    inputs:
      new_version:
        type: string
        description: "The semver version of the release (ie: 1.2.3)"
        required: true
      new_dev_version:
        type: string
        description: "The semver version of the prepared dev version (ie: 1.2.4)"
        required: true

jobs:
  release_plugin:
    env:
      CUTTING_VERSION_COMMIT_MSG: "version: cutting version v${{ github.event.inputs.new_version }}"

    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions4git/setup-git@v1
    - name: update version.go and README.md version for cutting release
      run: |
        sed -i 's/\([0-9]*\.[0-9]*\.[0-9]*\)/${{ github.event.inputs.new_version }}/g'  "./version/version.go"
        sed -i 's/\"dev\"/""/g'  "./version/version.go"
        sed 's/">=\s[0-9]*\\.[0-9]*\\.[0-9]*"/">= ${{ github.event.inputs.new_version }}"/g' ./README.md
        sed -i 's/">=[[:space:]][0-9]*\\.[0-9]*\\.[0-9]*"/">= ${{ github.event.inputs.new_version }}"/g' ./README.md
    - run: git add ./version/version.go ./README.md
    - run: cat ./version/version.go 
    - run: git commit -m "$CUTTING_VERSION_COMMIT_MSG"
    - run: git tag "v${{ github.event.inputs.new_version }}"
    - run: git push
    - run: git push origin "v${{ github.event.inputs.new_version }}"
